version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "/srv/armitage/postgres:/var/lib/postgresql/data"

  armitage:
    image: nicof2000/armitage
    restart: always
    depends_on:
      - postgres
    ports:
      - "4000-4100:4000-4100"    # exploitation ports
      - 55553:55553              # teamserver port
    environment:
      LHOST: 123.123.123.123     # your external ip, required for teamserver start, default lhost
      LPORT: 4000                # default lport
      TEAMSERVER_PASSWORD: secret
